// ============================================================
// Charlie MJ Video Downloader - Media Service
// ============================================================
// Purpose:
// - Uses yt-dlp to analyze media URLs.
// - Extracts available video/audio formats.
// - Extracts subtitle language information.
// - Starts URL-based media downloads.
// - Supports video, audio-only, and specific format downloads.
//
// Main flow:
//
// Frontend
//    ↓
// commands.rs
//    ↓
// media.rs
//    ↓
// yt-dlp.exe
//    ↓
// Media information / Downloaded file
// ============================================================

// Application models used to represent media information
// and individual downloadable formats.
use crate::models::{MediaFormat, MediaInfo};

// Used to parse the JSON output generated by yt-dlp.
use serde_json::Value;

// Standard library types used for locating external tools
// and controlling process input/output.
use std::{path::PathBuf, process::Stdio};

// Tokio's asynchronous process API allows yt-dlp to run
// without blocking the Tauri application.
use tokio::process::Command;


// ------------------------------------------------------------
// Locate External Tool
// ------------------------------------------------------------
// Returns the full path to an external tool such as:
//
// yt-dlp.exe
//
// Tool lookup order:
//
// 1. CHARLIE_MJ_TOOLS_DIR environment variable
// 2. "tools" directory next to the application executable
//
// This allows the application to work with both development
// and packaged/release installations.
fn tool(name: &str) -> PathBuf {
    // The packaged Tauri app sets CHARLIE_MJ_TOOLS_DIR during startup.
    // Keep this fallback resolver defensive so an installed build can
    // still find bundled tools if the environment variable is unavailable.
    if let Ok(dir) = std::env::var("CHARLIE_MJ_TOOLS_DIR") {
        let candidate = PathBuf::from(dir).join(name);
        if candidate.exists() {
            return candidate;
        }
    }

    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(PathBuf::from))
        .unwrap_or_default();

    let candidates = [
        exe_dir.join("resources").join("tools").join(name),
        exe_dir.join("tools").join(name),
        exe_dir.join("..\\resources\\tools").join(name),
    ];

    candidates
        .into_iter()
        .find(|p| p.exists())
        .unwrap_or_else(|| exe_dir.join("resources").join("tools").join(name))
}


// ============================================================
// Analyze Media URL
// ============================================================
// Uses yt-dlp to inspect a URL without downloading the media.
//
// The returned MediaInfo contains information such as:
//
// - Media ID
// - Title
// - Uploader
// - Duration
// - Thumbnail
// - Available formats
// - Subtitle languages
//
// yt-dlp produces the raw metadata as JSON, which is then
// converted into the application's Rust models.
pub async fn analyze(url: &str) -> Result<MediaInfo, String> {

    // --------------------------------------------------------
    // Run yt-dlp Metadata Analysis
    // --------------------------------------------------------
    // Arguments:
    //
    // --dump-single-json
    //     Return media information as one JSON object.
    //
    // --no-playlist
    //     Analyze only the supplied media item rather than
    //     processing a playlist.
    //
    // --skip-download
    //     Do not download the media.
    //
    // url
    //     URL being analyzed.
    let output = Command::new(tool("yt-dlp.exe"))
        .args([
            "--dump-single-json",
            "--no-playlist",
            "--skip-download",
            url
        ])

        // Capture standard output because it contains the
        // JSON metadata generated by yt-dlp.
        .stdout(Stdio::piped())

        // Capture standard error so useful yt-dlp error
        // messages can be returned to the application.
        .stderr(Stdio::piped())

        // Execute yt-dlp asynchronously and wait for it to
        // finish.
        .output()
        .await

        // Convert process-start errors into a readable message.
        .map_err(|e| format!("Unable to start yt-dlp: {e}"))?;

    // --------------------------------------------------------
    // Check yt-dlp Result
    // --------------------------------------------------------
    // A non-zero exit status means yt-dlp could not analyze
    // the supplied URL.
    if !output.status.success() {

        // Return the error message produced by yt-dlp.
        return Err(
            String::from_utf8_lossy(&output.stderr)
                .trim()
                .to_string()
        );
    }

    // --------------------------------------------------------
    // Parse yt-dlp JSON
    // --------------------------------------------------------
    // Convert yt-dlp's stdout into a generic JSON value.
    //
    // The JSON structure contains the media metadata and
    // available formats.
    let raw: Value = serde_json::from_slice(&output.stdout)
        .map_err(|e| format!("Invalid yt-dlp JSON: {e}"))?;

    // --------------------------------------------------------
    // Extract Available Formats
    // --------------------------------------------------------
    // yt-dlp can return many different formats, including:
    //
    // - Video-only formats
    // - Audio-only formats
    // - Combined video/audio formats
    // - Different resolutions
    // - Different codecs
    // - Different frame rates
    //
    // Convert each format into the application's MediaFormat
    // structure.
    let formats = raw["formats"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|f| MediaFormat {

            // yt-dlp format identifier used when requesting
            // a specific format.
            id: f["format_id"]
                .as_str()
                .unwrap_or_default()
                .to_string(),

            // File/container extension such as mp4, webm, m4a,
            // or other supported formats.
            extension: f["ext"]
                .as_str()
                .unwrap_or_default()
                .to_string(),

            // Human-readable resolution such as 1920x1080.
            resolution: f["resolution"]
                .as_str()
                .map(str::to_string),

            // Frames per second when provided by yt-dlp.
            fps: f["fps"].as_f64(),

            // Prefer the exact filesize when available.
            //
            // If exact filesize is unavailable, use the
            // approximate filesize provided by yt-dlp.
            filesize: f["filesize"]
                .as_u64()
                .or_else(|| f["filesize_approx"].as_u64()),

            // Video codec, for example avc1 or vp9.
            vcodec: f["vcodec"]
                .as_str()
                .map(str::to_string),

            // Audio codec, for example opus or aac.
            acodec: f["acodec"]
                .as_str()
                .map(str::to_string),

            // Audio bitrate in kbps when available.
            abr: f["abr"].as_f64(),

            // Additional format information supplied by yt-dlp.
            note: f["format_note"]
                .as_str()
                .map(str::to_string),
        })
        .collect();

    // --------------------------------------------------------
    // Extract Subtitle Languages
    // --------------------------------------------------------
    // yt-dlp returns subtitles as an object where each key is
    // a language code.
    //
    // Example:
    //
    // "subtitles": {
    //     "en": [...],
    //     "tr": [...]
    // }
    //
    // The application only needs the available language keys
    // at this stage.
    let subtitles = raw["subtitles"]
        .as_object()
        .map(|m| m.keys().cloned().collect())
        .unwrap_or_default();

    // --------------------------------------------------------
    // Build MediaInfo
    // --------------------------------------------------------
    // Convert the collected metadata into the application's
    // MediaInfo model and return it to the caller.
    Ok(MediaInfo {

        // Unique media identifier from yt-dlp.
        id: raw["id"]
            .as_str()
            .unwrap_or_default()
            .to_string(),

        // Media title.
        //
        // Use "Untitled" when yt-dlp does not provide a title.
        title: raw["title"]
            .as_str()
            .unwrap_or("Untitled")
            .to_string(),

        // Uploader/channel name when available.
        uploader: raw["uploader"]
            .as_str()
            .map(str::to_string),

        // Media duration in seconds.
        duration: raw["duration"].as_f64(),

        // Thumbnail URL when available.
        thumbnail: raw["thumbnail"]
            .as_str()
            .map(str::to_string),

        // Canonical webpage URL returned by yt-dlp.
        //
        // Fall back to the original input URL if yt-dlp does
        // not provide one.
        webpage_url: raw["webpage_url"]
            .as_str()
            .unwrap_or(url)
            .to_string(),

        // List of downloadable formats.
        formats,

        // List of available subtitle language codes.
        subtitles,
    })
}


// ============================================================
// Download Media
// ============================================================
// Uses yt-dlp to download media from a URL.
//
// Supported modes:
//
// 1. Audio-only:
//    format_id = "bestaudio"
//    → downloads best audio and converts it to MP3.
//
// 2. Specific format:
//    format_id = Some(format_id)
//    → downloads the requested yt-dlp format.
//
// 3. Default:
//    format_id = None
//    → downloads best available video + audio and merges
//      them into MP4.
//
// `output_template` controls the destination filename.
pub async fn download(
    url: &str,
    format_id: Option<&str>,
    output_template: Option<&str>
) -> Result<(), String> {

    // Create a new asynchronous yt-dlp process.
    let mut command = Command::new(tool("yt-dlp.exe"));

    // --------------------------------------------------------
    // General yt-dlp Options
    // --------------------------------------------------------
    // --newline makes progress output easier to process because
    // each progress update is written on a new line.
    //
    // --no-playlist prevents accidentally downloading an entire
    // playlist when a single media URL is provided.
    command.arg("--newline").arg("--no-playlist");

    // --------------------------------------------------------
    // Select Download Format
    // --------------------------------------------------------
    match format_id {

        // ----------------------------------------------------
        // Audio-only Download
        // ----------------------------------------------------
        // Download the best available audio stream and extract
        // it as MP3.
        Some("bestaudio") => {
            command.args([
                "-f",
                "bestaudio/best",
                "-x",
                "--audio-format",
                "mp3"
            ]);
        }

        // ----------------------------------------------------
        // Specific Format
        // ----------------------------------------------------
        // Use the exact format ID selected by the user.
        //
        // Example:
        //
        // -f 137
        //
        // The format ID normally comes from analyze().
        Some(id) => {
            command.args(["-f", id]);
        }

        // ----------------------------------------------------
        // Default Video Download
        // ----------------------------------------------------
        // Select the best available video and audio streams.
        //
        // If separate streams are selected, yt-dlp merges them
        // into an MP4 container.
        None => {
            command.args([
                "-f",
                "bestvideo*+bestaudio/best",
                "--merge-output-format",
                "mp4"
            ]);
        }
    }

    // --------------------------------------------------------
    // Configure Output Filename
    // --------------------------------------------------------
    // Use the caller's output template when provided.
    //
    // Otherwise use yt-dlp's title-based filename:
    //
    // %(title)s.%(ext)s
    command
        .arg("-o")
        .arg(output_template.unwrap_or("%(title)s.%(ext)s"));

    // Add the media URL as the final yt-dlp argument.
    command.arg(url);

    // --------------------------------------------------------
    // Execute Download
    // --------------------------------------------------------
    // Run yt-dlp asynchronously and wait for the download
    // process to complete.
    let output = command
        .output()
        .await
        .map_err(|e| e.to_string())?;

    // --------------------------------------------------------
    // Handle Download Result
    // --------------------------------------------------------
    if output.status.success() {

        // yt-dlp completed successfully.
        Ok(())

    } else {

        // Return yt-dlp's stderr output so the application can
        // report the reason for the failed download.
        Err(
            String::from_utf8_lossy(&output.stderr)
                .to_string()
        )
    }
}